longhorn:
  privateRegistry:
    registrySecret: image-pull-secret
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring.instance: "test-cluster-local"
  defaultSettings:
    defaultReplicaCount: "1"
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
  ingress:
    ingressClassName: traefik
    host: 192.168.97.3.traefik.me
    tls: true
    tlsSecret: tls-longhorn
    path: /longhorn
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      traefik.ingress.kubernetes.io/router.middlewares: longhorn-redirect-noslash@kubernetescrd,longhorn-strip-prefix@kubernetescrd
traefikPathRewrite:
  enabled: true
  pathPrefix: /longhorn

namespace:
  labels:
    project-name: "test-cluster"
    stage: "local"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
