traefik:
  deployment:
    imagePullSecrets:
      - name: image-pull-secret
  api:
    dashboard: true
    basePath: /traefik
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - websecure
      matchRule: Host(`172.18.0.3.traefik.me`) && PathPrefix(`/traefik`)
      middlewares:
        - name: oauth-auth
          namespace: traefik
      tls: {}
  extraObjects:
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: oauth-auth
        namespace: traefik
      spec:
        forwardAuth:
          address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/
          trustForwardHeader: true
          authResponseHeaders:
            - X-Auth-Request-User
            - X-Auth-Request-Email
            - Authorization
  metrics:
    prometheus:
      serviceMonitor:
        enabled: true
        additionalLabels:
          monitoring.instance: "local-cluster-dev"

namespace:
  labels:
    project-name: "local-cluster"
    stage: "dev"
