crds:
  install: true

namespace:
  labels:
    project-name: "spoke-1"
    stage: "local"

kyverno:
  global:
    imagePullSecrets:
      - name: image-pull-secret
  admissionController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring.instance: "spoke-1-local"
  backgroundController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring.instance: "spoke-1-local"
  cleanupController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring.instance: "spoke-1-local"
  reportsController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring.instance: "spoke-1-local"
  # FIX: https://github.com/kyverno/kyverno/issues/15116
  kyverno-api:
    labels:
      app.kubernetes.io/managed-by: Helm
    annotations:
      meta.helm.sh/release-name: kyverno
