---
apiVersion: v2
name: loki
description: Umbrella Chart for loki
type: application
version: 1.2.2
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.0.7
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 7.0.0
  - name: alloy
    repository: https://grafana.github.io/helm-charts
    version: 1.8.2
