traefik:
  api:
    basePath: /traefik
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - websecure
      matchRule: Host(`172.18.0.3.traefik.me`) && PathPrefix(`/traefik`)
      tls: {}
