---
metallb:
  controller:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  speaker:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    frr:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
    reloader:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
    frrMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
  prometheus:
    serviceMonitor:
      enabled: false
      controller:
  frr-k8s:
    prometheus:
      serviceMonitor:
        enabled: false
nodeSelectors: {}
namespace: {}
