namespace:
  labels:
    project-name: "spoke-1"
    stage: "local"
metrics-server:
  imagePullSecrets:
    - name: image-pull-secret
  serviceMonitor:
    additionalLabels:
      monitoring:
        instance: "spoke-1-local"
