namespace:
  labels:
    project-name: "test-cluster"
    stage: "dev"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
poolName: first-pool
addresses:
  - <no value>/32

metallb:
  imagePullSecrets:
    - name: image-pull-secret
  prometheus:
    serviceMonitor:
      speaker:
        additionalLabels:
          monitoring.instance: "test-cluster-dev"
      controller:
        additionalLabels:
          monitoring.instance: "test-cluster-dev"
