clusterSecretStores: {}
namespace:
  labels:
    project-name: "spoke-1"
    stage: "local"
external-secrets:
  certController:
    imagePullSecrets:
      - name: image-pull-secret
  webhook:
    imagePullSecrets:
      - name: image-pull-secret
  imagePullSecrets:
    - name: image-pull-secret
  serviceMonitor:
    enabled: true
    additionalLabels:
      monitoring.instance: "spoke-1-local"
  bitwarden-sdk-server:
    enabled: false
