namespace:
  labels:
    project-name: "spoke-1"
    stage: "local"


externalSecrets:
  secretStoreRef:
    kind: ClusterSecretStore
    name: spoke-1-local

  secretStores:
    spoke-1-local:
      kind: ClusterSecretStore
      name: spoke-1-local

  secrets:
    oauth2-credentials:
      secretStoreRef: spoke-1-local
      dataFrom:
        - remoteKey: spoke-1/local/oauth2-proxy/oauth2_credentials


oauth2-proxy:
  imagePullSecrets:
    - name: image-pull-secret
  config:
    existingSecret: oauth2-credentials
    configFile: |-
      reverse_proxy = true
      redirect_url = "https://192.168.97.4.traefik.me/oauth2/callback"
      email_domains = [ "*" ]
      cookie_secure = true
      upstreams = [ "static://200" ]
      github_org = "local"
      github_team = "local"
      provider = "github"
      scope = "read:user user:email read:org"
  ingress:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    enabled: true
    path: /oauth2
    pathType: Prefix
    hosts:
      - 192.168.97.4.traefik.me
    tls:
      - secretName: tls-oauth2-proxy
        hosts:
          - 192.168.97.4.traefik.me
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        monitoring.instance: "spoke-1-local"


middleware:
  name: oauth-auth
  namespace: oauth2-proxy

  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/
    trustForwardHeader: true

    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Authorization
