namespace:
  labels:
    project-name: "test-cluster"
    stage: "local"


externalSecrets:
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-cluster-local

  secretStores:
    test-cluster-local:
      kind: ClusterSecretStore
      name: test-cluster-local

  secrets:
    oauth2-credentials:
      secretStoreRef: test-cluster-local
      dataFrom:
        - remoteKey: oauth2_credentials


oauth2-proxy:
  imagePullSecrets:
    - name: image-pull-secret
  config:
    existingSecret: oauth2-credentials
    configFile: |-
      reverse_proxy = true
      redirect_url = "https://192.168.97.3.traefik.me/oauth2/callback"
      email_domains = [ "*" ]
      cookie_secure = true
      upstreams = [ "static://200" ]
      github_org = "local"
      github_team = "local"
      provider = "github"
      scope = "read:user user:email read:org"
  ingress:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    enabled: true
    path: /oauth2
    pathType: Prefix
    hosts:
      - 192.168.97.3.traefik.me
    tls:
      - secretName: tls-oauth2-proxy
        hosts:
          - 192.168.97.3.traefik.me
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        monitoring.instance: "test-cluster-local"


