longhorn:
  privateRegistry:
    registrySecret: image-pull-secret
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring.instance: "local-cluster-dev"
  defaultSettings:
    defaultReplicaCount: "1"
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    host: kubara.172.18.0.3.traefik.me
    tls: true
    tlsSecret: tls-longhorn
    path: "/longhorn(/|$)(.*)" # see path problems https://github.com/longhorn/longhorn/issues/1745
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-oauth-auth@kubernetescrd

namespace:
  labels:
    project-name: "local-cluster"
    stage: "dev"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
