externalSecrets:
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-cluster-local

  secretStores:
    test-cluster-local:
      kind: ClusterSecretStore
      name: test-cluster-local

  secrets:
    external-dns-webhook:
      secretStoreRef: test-cluster-local
      data:
        - remoteKey: dns_zone_admin
          remoteKeyProperty: project_id
          secretKey: PROJECT_ID
        - remoteKey: dns_zone_admin
          remoteKeyProperty: sa_key_json
          secretKey: SA_KEY_JSON

namespace:
  labels:
    project-name: "test-cluster"
    stage: "local"
external-dns:
  txtOwnerId: test-cluster-local
  domainFilters:
    - 172.18.0.3.traefik.me
  extraArgs:
    source:
      - traefik-proxy
    webhook-provider-url: http://localhost:8080
  rbac:
    create: true
    additionalPermissions:
      - apiGroups: ["traefik.io"]
        resources:
          - ingressroutes
          - ingressroutetcps
          - ingressrouteudps
          - tlsoptions
          - tlsstores
        verbs: ["get", "watch", "list"]
      - apiGroups: [""]
        resources:
          - "namespaces"
        verbs: ["get", "watch", "list"]
  extraVolumes:
    - name: stackit-sa-authentication
      secret:
        secretName: external-dns-webhook
        items:
          - key: SA_KEY_JSON
            path: sa_key.json
  global:
    imagePullSecrets:
      - name: image-pull-secret
    security:
      allowInsecureImages: true
  provider:
    webhook:
      image:
        repository: ghcr.io/stackitcloud/external-dns-stackit-webhook
        tag: v0.3.8
      extraVolumeMounts:
        - name: stackit-sa-authentication
          mountPath: /var/run/secrets/stackit
      env:
        - name: API_PORT
          value: "8080"
        - name: AUTH_KEY_PATH
          value: /var/run/secrets/stackit/sa_key.json
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: external-dns-webhook
              key: PROJECT_ID
  serviceMonitor:
    enabled: true
    additionalLabels:
      monitoring.instance: "test-cluster-local"
