---
letsencrypt: true
clusterIssuer:
  name: ""
  email: ""
  server: ""
  ingressClassName: ""
  customDefinition: {}
cert-manager:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
  prometheus:
    servicemonitor:
      enabled: false
  installCRDs: true
  serviceAccount:
    automountServiceAccountToken: true
  webhook:
    timeoutSeconds: 15  # set timeout to 15 seconds because of gardener, see: https://github.com/gardener/gardener/blob/master/docs/usage/shoot/shoot_status.md#constraints
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 150Mi
      limits:
        memory: 150Mi
  startupapicheck:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
namespace: {}
