bootstrapValues:
  projects:
    test-cluster-local:
      sourceRepos:
        - "https://github.com/tuunit/kubara-local.git"
        - "https://charts.external-secrets.io/"
        - "https://charts.jetstack.io"
        - "https://prometheus-community.github.io/helm-charts"
        - "ghcr.io/traefik/helm"
        - "oci://ghcr.io/traefik/helm"
dexRestarter:
  enabled: false
argo-cd:
  dex:
    enabled: false
  redis:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 128Mi
  applicationSet:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 256Mi
  repoServer:
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 512Mi
    volumeMounts:
      - name: host-ca-certificates
        mountPath: /etc/ssl/certs/ca-certificates.crt
        readOnly: true
    volumes:
      - name: host-ca-certificates
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: File
  controller:
    resources:
      requests:
        memory: 1000Mi
      limits:
        memory: 1000Mi
  server:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 256Mi
    ingressGrpc:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: ""
      tls: false
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: ""
      tls: false
  configs:
    cm:
      url: http://172.18.0.3.traefik.me/argocd
    rbac:
      policy.default: role:admin
      policy.csv: ""
