namespace:
  labels:
    project-name: "test-cluster"
    stage: "local"
policy-reporter:
  imagePullSecrets:
    - name: image-pull-secret
  replicaCount: 1
  metrics:
    enabled: true
  monitoring:
    serviceMonitor:
      labels:
        monitoring.instance: "test-cluster-local"
  ui:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/app-root: /kyverno/#/
        traefik.ingress.kubernetes.io/router.middlewares: |-
            oauth2-proxy-oauth-auth@kubernetescrd,
            kyverno-policy-reporter-strip-kyverno-prefix@kubernetescrd
      hosts:
        - host: 172.18.0.2.traefik.me
          paths:
            - path: "/kyverno"
              pathType: Prefix
      tls:
        - secretName: tls-kyverno-ui
          hosts:
            - 172.18.0.2.traefik.me

middleware:
  name: strip-kyverno-prefix
  namespace: kyverno-policy-reporter

  stripPrefix:
    prefixes:
      - /kyverno
