kube-prometheus-stack:
  global:
    imagePullSecrets:
      - name: image-pull-secret
    imageRegistry: ""
  prometheusOperator:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
    prometheus:
      monitor:
        additionalLabels:
          monitoring.instance: test-cluster-dev
  prometheus:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
    ingress:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-oauth-auth@kubernetescrd
      enabled: true
      paths:
        - /prometheus
      pathType: ImplementationSpecific
      hosts:
        - 172.18.0.3.traefik.me
      tls:
        - secretName: tls-prometheus
          hosts:
            - 172.18.0.3.traefik.me


    prometheusSpec:
      retention: 10d
      serviceMonitorSelector:
        matchLabels:
          monitoring.instance: test-cluster-dev
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      externalUrl: https://172.18.0.3.traefik.me/prometheus
      routePrefix: /prometheus
    thanosServiceMonitor:
      serviceMonitor:
        additionalLabels:
          monitoring.instance: test-cluster-dev
  alertmanager:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
    ingress:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-oauth-auth@kubernetescrd
      enabled: true
      paths:
        - /alertmanager
      pathType: ImplementationSpecific
      hosts:
        - 172.18.0.3.traefik.me
      tls:
        - secretName: tls-alertmanager
          hosts:
            - 172.18.0.3.traefik.me


# Below is an example alertmanager.config section:
# It demonstrates an advanced routing setup that includes Microsoft Teams (v2), a watchdog receiver
# (e.g. for UptimeRobot) and a silenced route for informational alerts.
# This config use webhook urls from secret-files (see alertmanagerSpec below)
#
#    config:
#      route:
#        receiver: msteams-notifications  # Default receiver if no route matches
#        routes:
#          # 1. Silence all alerts named "InfoInhibitor"
#          - receiver: "null"
#            matchers:
#              - alertname =~ "InfoInhibitor"
#          # 2. Route "Watchdog" alerts to UptimeRobot with a short repeat interval
#          - receiver: uptimerobot
#            repeat_interval: 1m
#            matchers:
#              - alertname =~ "Watchdog"
#          # 3. Route all alerts with severity "warning" or "critical" to Microsoft Teams
#          - receiver: 'msteams-notifications'
#            matchers:
#              - severity =~ "warning|critical"
#            continue: true  # Continue to evaluate other routes after this one
#      receivers:
#        # Microsoft Teams v2 receiver using `msteamsv2_configs`
#        - name: 'msteams-notifications'
#          msteamsv2_configs:
#            - send_resolved: true
#              webhook_url_file: /etc/alertmanager/secrets/msteams-webhook-url
#        # Watchdog/Uptime monitoring receiver
#        - name: uptimerobot
#          webhook_configs:
#            - url_file: /etc/alertmanager/secrets/uptimerobot-webhook-url
#        # Null receiver to discard matched alerts
#        - name: "null"
#      # Optional: Use custom templates for consistent alert formatting
#      templates:
#        - /etc/alertmanager/config/*.tmpl

    alertmanagerSpec:
#      # secrets for alertmanager config webhook urls
#      secrets:
#        - msteams-webhook-url
#        - uptimerobot-webhook-url

      externalUrl: https://172.18.0.3.traefik.me/alertmanager
      routePrefix: /alertmanager

  kube-state-metrics:
    prometheus:
      monitor:
        additionalLabels:
          monitoring.instance: test-cluster-dev
  kubeApiServer:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  kubelet:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  kubeControllerManager:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  coreDns:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  kubeDns:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  kubeScheduler:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  thanosRuler:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: test-cluster-dev
  grafana:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    serviceMonitor:
      labels:
        monitoring.instance: test-cluster-dev
    ingress:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-oauth-auth@kubernetescrd
      enabled: true
      path: /grafana
      pathType: ImplementationSpecific
      hosts:
        - 172.18.0.3.traefik.me
      tls:
        - secretName: tls-grafana
          hosts:
            - 172.18.0.3.traefik.me
    envFromSecrets:
      - name: oauth2-credentials
    grafana.ini:
      server:
        root_url: https://172.18.0.3.traefik.me/grafana/
        serve_from_sub_path: true
      auth.github:
        name: "Github"
        enabled: true
        client_id: ${client-id}
        client_secret: ${client-secret}
        allow_sign_up: true
        auto_login: false
        scopes: "user:email,read:org"
        allowed_organizations: "[\"local\"]"
        role_attribute_path: contains(groups[*], '@local/local') && 'Admin' || 'Viewer'
    additionalDataSources:
      - access: proxy
        isDefault: false
        name: loki
        type: loki
        url: http://loki-headless.loki.svc.cluster.local:3100
        version: 1
prometheus-blackbox-exporter:
  image:
    pullSecrets:
      - image-pull-secret
  global:
    imageRegistry: quay.io

externalSecrets:
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-cluster-dev

  secretStores:
    test-cluster-dev:
      kind: ClusterSecretStore
      name: test-cluster-dev

  secrets:
    grafana-admin-credentials:
      secretStoreRef: test-cluster-dev
      dataFrom:
        - remoteKey: grafana_credentials
    oauth2-credentials:
      secretStoreRef: test-cluster-dev
      dataFrom:
        - remoteKey: grafana_oauth2_credentials

namespace:
  labels:
    project-name: "test-cluster"
    stage: "dev"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
