---
namespace: {}
kyverno:
  crds:
    migration:
      podResources:
  test:
    resources:
      limits:
        cpu:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  webhooksCleanup:
    resources:
      limits:
        cpu:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  admissionController:
    initContainer:
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
        limits:
          cpu:
          memory: 256Mi
    container:
      resources:
        requests:
          cpu: 50m
          memory: 384Mi
        limits:
          memory: 384Mi
    serviceMonitor:
      enabled: false
  backgroundController:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: false
  cleanupController:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: false
  reportsController:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: false
